/**
 * Tool Registry
 *
 * Central registry of all available tools with metadata.
 * Used by the frontend, backend, MCP server, and CLI.
 */

import type { ToolDefinition, ToolCategory, CategoryInfo } from '../types/index.js';

const MB = 1024 * 1024;
const GB = 1024 * MB;

// ─── Tool Definitions ────────────────────────────────────────

export const tools: ToolDefinition[] = [
  // ── PDF Tools ────────────────────────────────────────────
  {
    id: 'merge_pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document',
    category: 'pdf',
    icon: 'file-plus',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 50,
    maxFileSize: 2 * GB,
    tags: ['merge', 'combine', 'join'],
    parameters: [
      { name: 'outputFilename', type: 'string', label: 'Output Filename', description: 'Name for the merged PDF', required: false, default: 'merged.pdf', placeholder: 'merged.pdf' },
    ],
  },
  {
    id: 'split_pdf',
    name: 'Split PDF',
    description: 'Split a PDF into multiple files by page ranges',
    category: 'pdf',
    icon: 'scissors',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['split', 'separate', 'divide'],
    parameters: [
      { name: 'ranges', type: 'string', label: 'Page Ranges', description: 'e.g. "1-5,10-15" or leave empty to split every page', required: false, placeholder: '1-5,10-15' },
      { name: 'splitEvery', type: 'number', label: 'Split Every N Pages', description: 'Split into groups of N pages', required: false, min: 1 },
    ],
  },
  {
    id: 'compress_pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    category: 'pdf',
    icon: 'minimize-2',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['compress', 'reduce', 'optimize', 'shrink'],
    parameters: [
      { name: 'quality', type: 'select', label: 'Quality', description: 'Compression quality level', required: false, default: 'medium', options: [{ label: 'Low (smallest file)', value: 'low' }, { label: 'Medium (balanced)', value: 'medium' }, { label: 'High (best quality)', value: 'high' }] },
    ],
  },
  {
    id: 'rotate_pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages by 90°, 180°, or 270°',
    category: 'pdf',
    icon: 'rotate-cw',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['rotate', 'orientation'],
    parameters: [
      { name: 'angle', type: 'select', label: 'Rotation Angle', description: 'Clockwise rotation angle', required: true, default: 90, options: [{ label: '90°', value: 90 }, { label: '180°', value: 180 }, { label: '270°', value: 270 }] },
      { name: 'pages', type: 'string', label: 'Pages', description: 'Comma-separated page numbers (empty = all pages)', required: false, placeholder: '1,3,5' },
    ],
  },
  {
    id: 'extract_pages',
    name: 'Extract Pages',
    description: 'Extract specific pages from a PDF',
    category: 'pdf',
    icon: 'file-output',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['extract', 'pages'],
    parameters: [
      { name: 'pages', type: 'string', label: 'Pages', description: 'Comma-separated page numbers', required: true, placeholder: '1,3,5,7-10' },
    ],
  },
  {
    id: 'delete_pages',
    name: 'Delete Pages',
    description: 'Remove specific pages from a PDF',
    category: 'pdf',
    icon: 'file-minus',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['delete', 'remove', 'pages'],
    parameters: [
      { name: 'pages', type: 'string', label: 'Pages to Delete', description: 'Comma-separated page numbers to remove', required: true, placeholder: '2,4,6' },
    ],
  },
  {
    id: 'rearrange_pages',
    name: 'Rearrange Pages',
    description: 'Reorder pages in a PDF',
    category: 'pdf',
    icon: 'arrow-up-down',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['reorder', 'rearrange', 'sort'],
    parameters: [
      { name: 'order', type: 'string', label: 'New Page Order', description: 'New page order as comma-separated numbers', required: true, placeholder: '3,1,2,5,4' },
    ],
  },
  {
    id: 'extract_text',
    name: 'Extract Text',
    description: 'Extract all text content from a PDF',
    category: 'pdf',
    icon: 'file-text',
    inputFormats: ['.pdf'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['extract', 'text', 'content'],
    parameters: [],
  },
  {
    id: 'add_watermark',
    name: 'Add Watermark',
    description: 'Add a text watermark to every page of a PDF',
    category: 'pdf',
    icon: 'droplets',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['watermark', 'stamp', 'overlay'],
    parameters: [
      { name: 'text', type: 'string', label: 'Watermark Text', description: 'Text to display as watermark', required: true, placeholder: 'CONFIDENTIAL' },
      { name: 'fontSize', type: 'number', label: 'Font Size', description: 'Font size in points', required: false, default: 48, min: 8, max: 200 },
      { name: 'opacity', type: 'range', label: 'Opacity', description: 'Watermark opacity (0-1)', required: false, default: 0.3, min: 0, max: 1, step: 0.05 },
      { name: 'rotation', type: 'number', label: 'Rotation', description: 'Rotation angle in degrees', required: false, default: 45, min: 0, max: 360 },
      { name: 'position', type: 'select', label: 'Position', description: 'Watermark position', required: false, default: 'center', options: [{ label: 'Center', value: 'center' }, { label: 'Top Left', value: 'top-left' }, { label: 'Top Right', value: 'top-right' }, { label: 'Bottom Left', value: 'bottom-left' }, { label: 'Bottom Right', value: 'bottom-right' }] },
    ],
  },
  {
    id: 'add_page_numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to a PDF document',
    category: 'pdf',
    icon: 'hash',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['page numbers', 'numbering', 'footer', 'header'],
    parameters: [
      { name: 'position', type: 'select', label: 'Position', description: 'Position of page numbers', required: false, default: 'bottom-center', options: [{ label: 'Bottom Center', value: 'bottom-center' }, { label: 'Bottom Left', value: 'bottom-left' }, { label: 'Bottom Right', value: 'bottom-right' }, { label: 'Top Center', value: 'top-center' }, { label: 'Top Left', value: 'top-left' }, { label: 'Top Right', value: 'top-right' }] },
      { name: 'format', type: 'select', label: 'Format', description: 'Number format', required: false, default: 'numeric', options: [{ label: 'Numeric (1, 2, 3)', value: 'numeric' }, { label: 'Roman (I, II, III)', value: 'roman' }, { label: 'Alphabetic (A, B, C)', value: 'alpha' }] },
      { name: 'startNumber', type: 'number', label: 'Start From', description: 'Starting page number', required: false, default: 1, min: 1 },
      { name: 'fontSize', type: 'number', label: 'Font Size', description: 'Font size in points', required: false, default: 12, min: 6, max: 48 },
    ],
  },
  {
    id: 'password_protect',
    name: 'Password Protect',
    description: 'Add password protection to a PDF',
    category: 'pdf',
    icon: 'lock',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['password', 'protect', 'encrypt', 'security'],
    parameters: [
      { name: 'userPassword', type: 'string', label: 'Password', description: 'Password to open the PDF', required: true },
    ],
  },
  {
    id: 'pdf_metadata',
    name: 'PDF Metadata',
    description: 'View and edit PDF metadata (title, author, etc.)',
    category: 'pdf',
    icon: 'info',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf', '.json'],
    maxFiles: 1,
    maxFileSize: 2 * GB,
    tags: ['metadata', 'properties', 'info'],
    parameters: [
      { name: 'title', type: 'string', label: 'Title', description: 'Document title', required: false },
      { name: 'author', type: 'string', label: 'Author', description: 'Document author', required: false },
      { name: 'subject', type: 'string', label: 'Subject', description: 'Document subject', required: false },
    ],
  },
  {
    id: 'images_to_pdf',
    name: 'Images to PDF',
    description: 'Convert images into a PDF document',
    category: 'pdf',
    icon: 'image',
    inputFormats: ['.png', '.jpg', '.jpeg'],
    outputFormats: ['.pdf'],
    maxFiles: 100,
    maxFileSize: 500 * MB,
    tags: ['images', 'convert', 'photo', 'picture'],
    parameters: [
      { name: 'pageSize', type: 'select', label: 'Page Size', description: 'PDF page size', required: false, default: 'A4', options: [{ label: 'A4', value: 'A4' }, { label: 'Letter', value: 'Letter' }, { label: 'Fit to Image', value: 'fit' }] },
    ],
  },

  // ── Image Tools ──────────────────────────────────────────
  {
    id: 'resize_image',
    name: 'Resize Image',
    description: 'Resize images to specific dimensions while maintaining aspect ratio',
    category: 'image',
    icon: 'maximize-2',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif', '.heic'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['resize', 'scale', 'dimensions'],
    parameters: [
      { name: 'width', type: 'number', label: 'Width', description: 'Target width in pixels', required: false, min: 1, max: 16384, placeholder: '1920' },
      { name: 'height', type: 'number', label: 'Height', description: 'Target height in pixels', required: false, min: 1, max: 16384, placeholder: '1080' },
      { name: 'fit', type: 'select', label: 'Fit Mode', description: 'How to fit the image', required: false, default: 'inside', options: [{ label: 'Inside (fit within)', value: 'inside' }, { label: 'Cover (fill area)', value: 'cover' }, { label: 'Contain (letterbox)', value: 'contain' }, { label: 'Fill (stretch)', value: 'fill' }] },
    ],
  },
  {
    id: 'crop_image',
    name: 'Crop Image',
    description: 'Crop an image to specific dimensions',
    category: 'image',
    icon: 'crop',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['crop', 'cut', 'trim'],
    parameters: [
      { name: 'left', type: 'number', label: 'Left', description: 'Left offset in pixels', required: true, min: 0 },
      { name: 'top', type: 'number', label: 'Top', description: 'Top offset in pixels', required: true, min: 0 },
      { name: 'width', type: 'number', label: 'Width', description: 'Crop width in pixels', required: true, min: 1 },
      { name: 'height', type: 'number', label: 'Height', description: 'Crop height in pixels', required: true, min: 1 },
    ],
  },
  {
    id: 'rotate_image',
    name: 'Rotate Image',
    description: 'Rotate an image by any angle',
    category: 'image',
    icon: 'rotate-cw',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['rotate', 'angle', 'orientation'],
    parameters: [
      { name: 'angle', type: 'number', label: 'Angle', description: 'Rotation angle in degrees (clockwise)', required: true, min: 0, max: 360, default: 90 },
    ],
  },
  {
    id: 'flip_image',
    name: 'Flip Image',
    description: 'Flip an image horizontally or vertically',
    category: 'image',
    icon: 'flip-horizontal',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['flip', 'mirror'],
    parameters: [
      { name: 'direction', type: 'select', label: 'Direction', description: 'Flip direction', required: true, default: 'horizontal', options: [{ label: 'Horizontal', value: 'horizontal' }, { label: 'Vertical', value: 'vertical' }] },
    ],
  },
  {
    id: 'compress_image',
    name: 'Compress Image',
    description: 'Reduce image file size with adjustable quality',
    category: 'image',
    icon: 'minimize-2',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['compress', 'optimize', 'reduce'],
    parameters: [
      { name: 'quality', type: 'range', label: 'Quality', description: 'Output quality (1-100)', required: false, default: 80, min: 1, max: 100, step: 1 },
      { name: 'format', type: 'select', label: 'Output Format', description: 'Convert to format during compression', required: false, options: [{ label: 'Keep Original', value: '' }, { label: 'JPEG', value: 'jpeg' }, { label: 'PNG', value: 'png' }, { label: 'WebP', value: 'webp' }, { label: 'AVIF', value: 'avif' }] },
    ],
  },
  {
    id: 'convert_image',
    name: 'Convert Image',
    description: 'Convert images between formats (PNG, JPG, WebP, AVIF, TIFF, GIF)',
    category: 'image',
    icon: 'repeat',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif', '.heic'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff', '.gif'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['convert', 'format', 'transform'],
    parameters: [
      { name: 'format', type: 'select', label: 'Output Format', description: 'Target image format', required: true, options: [{ label: 'JPEG', value: 'jpeg' }, { label: 'PNG', value: 'png' }, { label: 'WebP', value: 'webp' }, { label: 'AVIF', value: 'avif' }, { label: 'TIFF', value: 'tiff' }, { label: 'GIF', value: 'gif' }] },
      { name: 'quality', type: 'range', label: 'Quality', description: 'Output quality (1-100)', required: false, default: 90, min: 1, max: 100, step: 1 },
    ],
  },
  {
    id: 'image_blur',
    name: 'Blur Image',
    description: 'Apply Gaussian blur to an image',
    category: 'image',
    icon: 'eye-off',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['blur', 'gaussian', 'smooth'],
    parameters: [
      { name: 'sigma', type: 'range', label: 'Blur Amount', description: 'Blur intensity (0.3-100)', required: false, default: 5, min: 0.3, max: 100, step: 0.1 },
    ],
  },
  {
    id: 'image_sharpen',
    name: 'Sharpen Image',
    description: 'Sharpen an image to enhance details',
    category: 'image',
    icon: 'zap',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['sharpen', 'enhance', 'detail'],
    parameters: [
      { name: 'sigma', type: 'range', label: 'Sharpness', description: 'Sharpening intensity', required: false, default: 2, min: 0.5, max: 10, step: 0.5 },
    ],
  },
  {
    id: 'image_adjust',
    name: 'Adjust Image',
    description: 'Adjust brightness, contrast, and saturation',
    category: 'image',
    icon: 'sliders',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['brightness', 'contrast', 'saturation', 'adjust'],
    parameters: [
      { name: 'brightness', type: 'range', label: 'Brightness', description: '0.5 = darker, 1 = normal, 2 = brighter', required: false, default: 1, min: 0.1, max: 3, step: 0.1 },
      { name: 'saturation', type: 'range', label: 'Saturation', description: '0 = grayscale, 1 = normal, 2 = vibrant', required: false, default: 1, min: 0, max: 3, step: 0.1 },
    ],
  },
  {
    id: 'image_grayscale',
    name: 'Grayscale',
    description: 'Convert an image to grayscale (black & white)',
    category: 'image',
    icon: 'contrast',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff', '.gif'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['grayscale', 'black and white', 'monochrome'],
    parameters: [],
  },
  {
    id: 'image_metadata',
    name: 'Image Metadata',
    description: 'View image metadata and EXIF data',
    category: 'image',
    icon: 'info',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif', '.heic'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['metadata', 'exif', 'info', 'properties'],
    parameters: [],
  },
  {
    id: 'remove_exif',
    name: 'Remove EXIF',
    description: 'Strip all EXIF metadata from an image for privacy',
    category: 'image',
    icon: 'shield',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.tiff'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['exif', 'metadata', 'privacy', 'strip'],
    parameters: [],
  },
  {
    id: 'generate_thumbnail',
    name: 'Generate Thumbnail',
    description: 'Create a thumbnail version of an image',
    category: 'image',
    icon: 'image',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif'],
    outputFormats: ['.jpg', '.png', '.webp'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['thumbnail', 'preview', 'small'],
    parameters: [
      { name: 'width', type: 'number', label: 'Width', description: 'Thumbnail width in pixels', required: false, default: 200, min: 16, max: 1024 },
      { name: 'height', type: 'number', label: 'Height', description: 'Thumbnail height in pixels', required: false, default: 200, min: 16, max: 1024 },
    ],
  },
  {
    id: 'batch_resize',
    name: 'Batch Resize',
    description: 'Resize multiple images at once',
    category: 'image',
    icon: 'layers',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.avif'],
    outputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff'],
    maxFiles: 50,
    maxFileSize: 200 * MB,
    tags: ['batch', 'resize', 'bulk', 'multiple'],
    parameters: [
      { name: 'width', type: 'number', label: 'Width', description: 'Target width', required: false, min: 1, max: 16384, placeholder: '1920' },
      { name: 'height', type: 'number', label: 'Height', description: 'Target height', required: false, min: 1, max: 16384, placeholder: '1080' },
      { name: 'fit', type: 'select', label: 'Fit Mode', description: 'How to fit the image', required: false, default: 'inside', options: [{ label: 'Inside (fit within)', value: 'inside' }, { label: 'Cover (fill area)', value: 'cover' }, { label: 'Contain (letterbox)', value: 'contain' }] },
    ],
  },

  // ── Data Tools ───────────────────────────────────────────
  {
    id: 'json_to_csv',
    name: 'JSON to CSV',
    description: 'Convert JSON arrays to CSV format',
    category: 'data',
    icon: 'table',
    inputFormats: ['.json'],
    outputFormats: ['.csv'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['json', 'csv', 'convert', 'table'],
    parameters: [
      { name: 'delimiter', type: 'select', label: 'Delimiter', description: 'Field separator', required: false, default: ',', options: [{ label: 'Comma (,)', value: ',' }, { label: 'Semicolon (;)', value: ';' }, { label: 'Tab', value: '\t' }, { label: 'Pipe (|)', value: '|' }] },
    ],
  },
  {
    id: 'csv_to_json',
    name: 'CSV to JSON',
    description: 'Convert CSV files to JSON format',
    category: 'data',
    icon: 'braces',
    inputFormats: ['.csv', '.tsv'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['csv', 'json', 'convert', 'parse'],
    parameters: [
      { name: 'header', type: 'boolean', label: 'First Row is Header', description: 'Treat first row as column names', required: false, default: true },
    ],
  },
  {
    id: 'json_to_xml',
    name: 'JSON to XML',
    description: 'Convert JSON data to XML format',
    category: 'data',
    icon: 'code',
    inputFormats: ['.json'],
    outputFormats: ['.xml'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['json', 'xml', 'convert'],
    parameters: [
      { name: 'rootName', type: 'string', label: 'Root Element', description: 'Name of the root XML element', required: false, default: 'root', placeholder: 'root' },
    ],
  },
  {
    id: 'xml_to_json',
    name: 'XML to JSON',
    description: 'Convert XML data to JSON format',
    category: 'data',
    icon: 'braces',
    inputFormats: ['.xml'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['xml', 'json', 'convert', 'parse'],
    parameters: [],
  },
  {
    id: 'json_to_yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON data to YAML format',
    category: 'data',
    icon: 'file-code',
    inputFormats: ['.json'],
    outputFormats: ['.yaml', '.yml'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['json', 'yaml', 'convert'],
    parameters: [],
  },
  {
    id: 'yaml_to_json',
    name: 'YAML to JSON',
    description: 'Convert YAML data to JSON format',
    category: 'data',
    icon: 'braces',
    inputFormats: ['.yaml', '.yml'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['yaml', 'json', 'convert'],
    parameters: [],
  },
  {
    id: 'validate_json',
    name: 'Validate JSON',
    description: 'Check if JSON data is valid and well-formed',
    category: 'data',
    icon: 'check-circle',
    inputFormats: ['.json'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['validate', 'check', 'json', 'lint'],
    parameters: [],
  },
  {
    id: 'format_json',
    name: 'Format JSON',
    description: 'Pretty-print and format JSON data',
    category: 'data',
    icon: 'align-left',
    inputFormats: ['.json'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['format', 'prettify', 'indent', 'json'],
    parameters: [
      { name: 'indent', type: 'select', label: 'Indent', description: 'Indentation size', required: false, default: 2, options: [{ label: '2 spaces', value: 2 }, { label: '4 spaces', value: 4 }] },
    ],
  },
  {
    id: 'minify_json',
    name: 'Minify JSON',
    description: 'Minify JSON by removing whitespace',
    category: 'data',
    icon: 'minimize',
    inputFormats: ['.json'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['minify', 'compact', 'json', 'reduce'],
    parameters: [],
  },
  {
    id: 'format_xml',
    name: 'Format XML',
    description: 'Pretty-print and format XML data',
    category: 'data',
    icon: 'align-left',
    inputFormats: ['.xml'],
    outputFormats: ['.xml'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['format', 'prettify', 'xml'],
    parameters: [],
  },
  {
    id: 'markdown_to_html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown documents to styled HTML',
    category: 'data',
    icon: 'globe',
    inputFormats: ['.md', '.markdown'],
    outputFormats: ['.html'],
    maxFiles: 1,
    maxFileSize: 100 * MB,
    tags: ['markdown', 'html', 'convert', 'document'],
    parameters: [
      { name: 'wrapInHtml', type: 'boolean', label: 'Full HTML Document', description: 'Wrap in complete HTML with styling', required: false, default: true },
    ],
  },
  {
    id: 'html_to_markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML pages to Markdown format',
    category: 'data',
    icon: 'file-text',
    inputFormats: ['.html', '.htm'],
    outputFormats: ['.md'],
    maxFiles: 1,
    maxFileSize: 100 * MB,
    tags: ['html', 'markdown', 'convert', 'document'],
    parameters: [],
  },

  // ── Document Tools (Phase 2) ──────────────────────────────────
  {
    id: 'extract_docx_text',
    name: 'Extract Word Text',
    description: 'Extract raw text content from DOCX documents',
    category: 'document',
    icon: 'file-text',
    inputFormats: ['.docx', '.doc'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['word', 'docx', 'text', 'extract'],
    parameters: [],
  },
  {
    id: 'docx_to_html',
    name: 'Word to HTML',
    description: 'Convert DOCX documents to HTML with formatting',
    category: 'document',
    icon: 'globe',
    inputFormats: ['.docx', '.doc'],
    outputFormats: ['.html'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['word', 'docx', 'html', 'convert'],
    parameters: [],
  },
  {
    id: 'extract_docx_images',
    name: 'Extract Word Images',
    description: 'Extract all embedded images from a Word document',
    category: 'document',
    icon: 'image',
    inputFormats: ['.docx'],
    outputFormats: ['.png', '.jpg'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['word', 'docx', 'images', 'extract', 'photos'],
    parameters: [],
  },

  // ── Spreadsheet Tools (Phase 2) ───────────────────────────────
  {
    id: 'excel_to_csv',
    name: 'Excel to CSV',
    description: 'Convert an Excel workbook sheet to CSV',
    category: 'spreadsheet',
    icon: 'table',
    inputFormats: ['.xlsx', '.xls'],
    outputFormats: ['.csv'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['excel', 'xlsx', 'csv', 'convert', 'sheet'],
    parameters: [
      { name: 'sheetName', type: 'string', label: 'Sheet Name', description: 'Name of the sheet to convert (leave empty for first sheet)', required: false, placeholder: 'Sheet1' },
    ],
  },
  {
    id: 'csv_to_excel',
    name: 'CSV to Excel',
    description: 'Convert a CSV file to an Excel XLSX workbook',
    category: 'spreadsheet',
    icon: 'file-text',
    inputFormats: ['.csv', '.tsv'],
    outputFormats: ['.xlsx'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['csv', 'excel', 'xlsx', 'convert'],
    parameters: [],
  },
  {
    id: 'excel_to_json',
    name: 'Excel to JSON',
    description: 'Convert Excel spreadsheet data to JSON array of objects',
    category: 'spreadsheet',
    icon: 'braces',
    inputFormats: ['.xlsx', '.xls'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['excel', 'xlsx', 'json', 'convert'],
    parameters: [
      { name: 'sheetName', type: 'string', label: 'Sheet Name', description: 'Name of the sheet to convert (leave empty for first sheet)', required: false, placeholder: 'Sheet1' },
    ],
  },
  {
    id: 'merge_excel_sheets',
    name: 'Merge Excel Workbooks',
    description: 'Combine multiple Excel workbooks/sheets into a single workbook',
    category: 'spreadsheet',
    icon: 'layers',
    inputFormats: ['.xlsx'],
    outputFormats: ['.xlsx'],
    maxFiles: 20,
    maxFileSize: 500 * MB,
    tags: ['excel', 'xlsx', 'merge', 'combine'],
    parameters: [
      { name: 'outputFilename', type: 'string', label: 'Output Filename', description: 'Name for merged workbook', required: false, default: 'merged_workbook.xlsx' },
    ],
  },
  {
    id: 'remove_csv_duplicates',
    name: 'Remove CSV Duplicates',
    description: 'Remove duplicate rows from a CSV file',
    category: 'spreadsheet',
    icon: 'shield',
    inputFormats: ['.csv'],
    outputFormats: ['.csv'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['csv', 'dedupe', 'duplicates', 'clean'],
    parameters: [
      { name: 'columnHeader', type: 'string', label: 'Unique Column Header', description: 'Column to check for duplicates (leave empty to check full row)', required: false, placeholder: 'Email' },
    ],
  },
  {
    id: 'extract_docx_hyperlinks',
    name: 'Extract Word Links',
    description: 'Extract all embedded URLs and hyperlinks from a Word document',
    category: 'document',
    icon: 'globe',
    inputFormats: ['.docx'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['word', 'docx', 'links', 'urls', 'extract'],
    parameters: [],
  },
  {
    id: 'docx_to_markdown',
    name: 'Word to Markdown',
    description: 'Convert DOCX Word documents to Markdown format',
    category: 'document',
    icon: 'file-code',
    inputFormats: ['.docx'],
    outputFormats: ['.md'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['word', 'docx', 'markdown', 'convert'],
    parameters: [],
  },
  {
    id: 'text_to_docx',
    name: 'Text to Word',
    description: 'Convert plain text or Markdown files into a Word DOCX document',
    category: 'document',
    icon: 'file-text',
    inputFormats: ['.txt', '.md'],
    outputFormats: ['.docx'],
    maxFiles: 1,
    maxFileSize: 100 * MB,
    tags: ['text', 'markdown', 'word', 'docx', 'convert'],
    parameters: [],
  },
  {
    id: 'json_to_excel',
    name: 'JSON to Excel',
    description: 'Convert JSON array of objects into a formatted Excel XLSX workbook',
    category: 'spreadsheet',
    icon: 'table',
    inputFormats: ['.json'],
    outputFormats: ['.xlsx'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['json', 'excel', 'xlsx', 'convert'],
    parameters: [],
  },
  {
    id: 'transpose_sheet',
    name: 'Transpose Spreadsheet',
    description: 'Transpose rows and columns in a CSV / spreadsheet',
    category: 'spreadsheet',
    icon: 'repeat',
    inputFormats: ['.csv'],
    outputFormats: ['.csv'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['csv', 'excel', 'transpose', 'swap', 'rows', 'columns'],
    parameters: [],
  },
  {
    id: 'extract_pptx_text',
    name: 'Extract PPTX Text',
    description: 'Extract raw text from all slides in a PowerPoint presentation',
    category: 'presentation',
    icon: 'file-text',
    inputFormats: ['.pptx', '.ppt'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pptx', 'powerpoint', 'presentation', 'text', 'extract'],
    parameters: [],
  },
  {
    id: 'extract_pptx_notes',
    name: 'Extract Speaker Notes',
    description: 'Extract speaker notes from PowerPoint presentation slides',
    category: 'presentation',
    icon: 'file-text',
    inputFormats: ['.pptx'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pptx', 'powerpoint', 'notes', 'speaker notes', 'extract'],
    parameters: [],
  },
  {
    id: 'extract_pptx_images',
    name: 'Extract PPTX Images',
    description: 'Extract embedded images and graphics from PowerPoint slides',
    category: 'presentation',
    icon: 'image',
    inputFormats: ['.pptx'],
    outputFormats: ['.png', '.jpg'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pptx', 'powerpoint', 'images', 'graphics', 'photos', 'extract'],
    parameters: [],
  },
  {
    id: 'word_count',
    name: 'Text & Word Analysis',
    description: 'Calculate word count, character count, sentence count, and reading time',
    category: 'text',
    icon: 'info',
    inputFormats: ['.txt', '.md', '.html', '.json', '.csv'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 100 * MB,
    tags: ['word count', 'statistics', 'readability', 'analysis'],
    parameters: [],
  },
  {
    id: 'pdf_to_docx',
    name: 'PDF to Word (DOCX)',
    description: 'Convert PDF document to an editable Word DOCX file',
    category: 'pdf',
    icon: 'file-text',
    inputFormats: ['.pdf'],
    outputFormats: ['.docx'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['pdf', 'word', 'docx', 'convert'],
    parameters: [],
  },
  {
    id: 'pdf_to_html',
    name: 'PDF to HTML',
    description: 'Convert PDF document content into a styled HTML web page',
    category: 'pdf',
    icon: 'globe',
    inputFormats: ['.pdf'],
    outputFormats: ['.html'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['pdf', 'html', 'convert', 'web'],
    parameters: [],
  },
  {
    id: 'excel_to_html',
    name: 'Excel to HTML Table',
    description: 'Convert Excel spreadsheet to an HTML formatted table',
    category: 'spreadsheet',
    icon: 'table',
    inputFormats: ['.xlsx', '.xls'],
    outputFormats: ['.html'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['excel', 'xlsx', 'html', 'table', 'convert'],
    parameters: [],
  },
  {
    id: 'pdf_to_images',
    name: 'PDF to JPG / Images',
    description: 'Extract embedded photos, graphics, and page images from PDF to JPG/PNG',
    category: 'pdf',
    icon: 'image',
    inputFormats: ['.pdf'],
    outputFormats: ['.jpg', '.png'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'jpg', 'jpeg', 'png', 'images', 'extract', 'convert'],
    parameters: [],
  },
  {
    id: 'create_zip',
    name: 'Create ZIP Archive',
    description: 'Compress multiple files into a single ZIP archive',
    category: 'archive',
    icon: 'archive',
    inputFormats: ['*'],
    outputFormats: ['.zip'],
    maxFiles: 100,
    maxFileSize: 1000 * MB,
    tags: ['zip', 'archive', 'compress'],
    parameters: [
      { name: 'outputFilename', type: 'string', label: 'ZIP Filename', description: 'Name of the ZIP file', required: false, default: 'archive.zip' },
    ],
  },
  {
    id: 'extract_zip',
    name: 'Extract ZIP Archive',
    description: 'Extract all files and folders from a ZIP archive',
    category: 'archive',
    icon: 'folder-minus',
    inputFormats: ['.zip'],
    outputFormats: ['*'],
    maxFiles: 1,
    maxFileSize: 1000 * MB,
    tags: ['zip', 'unzip', 'extract', 'archive'],
    parameters: [],
  },
  {
    id: 'list_archive_contents',
    name: 'List Archive Contents',
    description: 'Inspect files and folders inside a ZIP archive without extracting',
    category: 'archive',
    icon: 'list',
    inputFormats: ['.zip'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 1000 * MB,
    tags: ['zip', 'list', 'archive', 'inspect'],
    parameters: [],
  },
  {
    id: 'convert_audio',
    name: 'Convert Audio Format',
    description: 'Convert audio files between MP3, WAV, AAC, OGG, FLAC, and M4A formats',
    category: 'audio',
    icon: 'music',
    inputFormats: ['.mp3', '.wav', '.aac', '.ogg', '.flac', '.m4a'],
    outputFormats: ['.mp3', '.wav', '.aac', '.ogg', '.flac', '.m4a'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['audio', 'mp3', 'wav', 'aac', 'convert'],
    parameters: [
      { name: 'targetFormat', type: 'select', label: 'Target Format', description: 'Format to convert audio to', required: true, default: 'mp3', options: [
        { label: 'MP3', value: 'mp3' },
        { label: 'WAV', value: 'wav' },
        { label: 'AAC', value: 'aac' },
        { label: 'OGG', value: 'ogg' },
        { label: 'FLAC', value: 'flac' },
      ]},
    ],
  },
  {
    id: 'extract_audio_from_video',
    name: 'Extract Audio from Video',
    description: 'Extract high-quality audio stream from MP4, MKV, AVI, or MOV video',
    category: 'audio',
    icon: 'volume-2',
    inputFormats: ['.mp4', '.mkv', '.avi', '.mov', '.webm'],
    outputFormats: ['.mp3', '.wav', '.aac'],
    maxFiles: 1,
    maxFileSize: 1000 * MB,
    tags: ['video', 'audio', 'mp3', 'extract'],
    parameters: [
      { name: 'targetFormat', type: 'select', label: 'Audio Format', description: 'Extracted audio format', required: false, default: 'mp3', options: [
        { label: 'MP3', value: 'mp3' },
        { label: 'WAV', value: 'wav' },
        { label: 'AAC', value: 'aac' },
      ]},
    ],
  },
  {
    id: 'compress_video',
    name: 'Compress Video',
    description: 'Reduce video file size using H.264 video compression',
    category: 'video',
    icon: 'film',
    inputFormats: ['.mp4', '.mkv', '.avi', '.mov', '.webm'],
    outputFormats: ['.mp4'],
    maxFiles: 1,
    maxFileSize: 2000 * MB,
    tags: ['video', 'mp4', 'compress', 'reduce size'],
    parameters: [],
  },
  {
    id: 'generate_video_thumbnail',
    name: 'Video Frame Thumbnail',
    description: 'Extract a high-resolution JPG thumbnail image from any video frame timestamp',
    category: 'video',
    icon: 'image',
    inputFormats: ['.mp4', '.mkv', '.avi', '.mov', '.webm'],
    outputFormats: ['.jpg'],
    maxFiles: 1,
    maxFileSize: 2000 * MB,
    tags: ['video', 'thumbnail', 'frame', 'jpg', 'image'],
    parameters: [
      { name: 'timestamp', type: 'string', label: 'Timestamp (HH:MM:SS)', description: 'Timestamp frame to extract', required: false, default: '00:00:01' },
    ],
  },
  {
    id: 'trim_audio',
    name: 'Trim Audio',
    description: 'Cut audio clip between start and end timestamps',
    category: 'audio',
    icon: 'scissors',
    inputFormats: ['.mp3', '.wav', '.aac', '.ogg', '.flac', '.m4a'],
    outputFormats: ['.mp3', '.wav', '.aac', '.ogg', '.flac'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['audio', 'trim', 'cut', 'crop'],
    parameters: [
      { name: 'startTime', type: 'string', label: 'Start Time (HH:MM:SS)', description: 'Start timestamp', required: false, placeholder: '00:00:10' },
      { name: 'endTime', type: 'string', label: 'End Time (HH:MM:SS)', description: 'End timestamp', required: false, placeholder: '00:01:30' },
    ],
  },
  {
    id: 'change_audio_speed',
    name: 'Change Audio Speed',
    description: 'Adjust audio playback speed (0.5x slow-motion to 2.0x fast-forward)',
    category: 'audio',
    icon: 'zap',
    inputFormats: ['.mp3', '.wav', '.aac', '.ogg', '.flac', '.m4a'],
    outputFormats: ['.mp3', '.wav', '.aac'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['audio', 'speed', 'fast', 'slow'],
    parameters: [],
  },
  {
    id: 'audio_to_waveform',
    name: 'Audio Waveform Image',
    description: 'Generate a visual waveform PNG image of any audio track',
    category: 'audio',
    icon: 'activity',
    inputFormats: ['.mp3', '.wav', '.aac', '.ogg', '.flac', '.m4a'],
    outputFormats: ['.png'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['audio', 'waveform', 'visual', 'png', 'image'],
    parameters: [],
  },
  {
    id: 'video_to_gif',
    name: 'Video to Animated GIF',
    description: 'Convert video clip into a smooth animated GIF file',
    category: 'video',
    icon: 'play-circle',
    inputFormats: ['.mp4', '.mkv', '.avi', '.mov', '.webm'],
    outputFormats: ['.gif'],
    maxFiles: 1,
    maxFileSize: 1000 * MB,
    tags: ['video', 'gif', 'animation', 'convert'],
    parameters: [],
  },
  {
    id: 'gif_to_video',
    name: 'GIF to MP4 Video',
    description: 'Convert animated GIF files into lightweight MP4 video clips',
    category: 'video',
    icon: 'video',
    inputFormats: ['.gif'],
    outputFormats: ['.mp4'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['gif', 'video', 'mp4', 'convert'],
    parameters: [],
  },
  {
    id: 'trim_video',
    name: 'Trim Video Clip',
    description: 'Cut video clip between start and end timestamps',
    category: 'video',
    icon: 'scissors',
    inputFormats: ['.mp4', '.mkv', '.avi', '.mov', '.webm'],
    outputFormats: ['.mp4'],
    maxFiles: 1,
    maxFileSize: 2000 * MB,
    tags: ['video', 'trim', 'cut', 'clip'],
    parameters: [
      { name: 'startTime', type: 'string', label: 'Start Time (HH:MM:SS)', description: 'Start timestamp', required: false, placeholder: '00:00:05' },
      { name: 'endTime', type: 'string', label: 'End Time (HH:MM:SS)', description: 'End timestamp', required: false, placeholder: '00:00:45' },
    ],
  },
  {
    id: 'mute_video',
    name: 'Mute Video (Strip Audio)',
    description: 'Remove audio track from video file to create a silent video',
    category: 'video',
    icon: 'volume-x',
    inputFormats: ['.mp4', '.mkv', '.avi', '.mov', '.webm'],
    outputFormats: ['.mp4'],
    maxFiles: 1,
    maxFileSize: 2000 * MB,
    tags: ['video', 'mute', 'silent', 'strip audio'],
    parameters: [],
  },
  {
    id: 'compress_gzip',
    name: 'GZIP Compress File',
    description: 'Compress any single file using GZIP compression algorithm (.gz)',
    category: 'archive',
    icon: 'archive',
    inputFormats: ['*'],
    outputFormats: ['.gz'],
    maxFiles: 1,
    maxFileSize: 1000 * MB,
    tags: ['gzip', 'gz', 'compress', 'archive'],
    parameters: [],
  },
  {
    id: 'decompress_gzip',
    name: 'GZIP Decompress File',
    description: 'Decompress GZIP (.gz) archive file',
    category: 'archive',
    icon: 'folder-minus',
    inputFormats: ['.gz'],
    outputFormats: ['*'],
    maxFiles: 1,
    maxFileSize: 1000 * MB,
    tags: ['gzip', 'gunzip', 'decompress', 'extract'],
    parameters: [],
  },
  {
    id: 'extract_text_from_image_ocr',
    name: 'Image OCR Text Extractor',
    description: 'Perform Optical Character Recognition on PNG, JPG, or TIFF images to extract text',
    category: 'ocr',
    icon: 'scan',
    inputFormats: ['.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.webp'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['ocr', 'text', 'scan', 'extract', 'tesseract'],
    parameters: [
      { name: 'language', type: 'string', label: 'Language Code', description: 'OCR language code (eng, spa, fra, deu, etc.)', required: false, default: 'eng' },
    ],
  },
  {
    id: 'hash_file',
    name: 'File Checksum Hashing',
    description: 'Calculate MD5, SHA1, SHA256, and SHA512 checksum hashes of any file',
    category: 'metadata',
    icon: 'shield',
    inputFormats: ['*'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 2000 * MB,
    tags: ['hash', 'md5', 'sha256', 'checksum', 'verify'],
    parameters: [],
  },
  {
    id: 'summarize_text',
    name: 'AI Document Summarizer',
    description: 'Summarize long text, documents, or extracted PDF content into key bullet points',
    category: 'ai',
    icon: 'brain',
    inputFormats: ['.txt', '.md', '.html', '.json', '.pdf'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['ai', 'summarize', 'summary', 'nlp', 'text'],
    parameters: [
      { name: 'maxSentences', type: 'number', label: 'Max Sentences', description: 'Number of summary sentences to generate', required: false, default: 5 },
    ],
  },
  {
    id: 'extract_keywords',
    name: 'AI Keyword Extractor',
    description: 'Extract top keywords and key phrases from any document or text file',
    category: 'ai',
    icon: 'tag',
    inputFormats: ['.txt', '.md', '.html', '.json'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['ai', 'keywords', 'nlp', 'extract', 'tags'],
    parameters: [],
  },
  {
    id: 'sentiment_analysis',
    name: 'AI Sentiment Analysis',
    description: 'Analyze sentiment (Positive, Negative, Neutral) and emotion scores of text',
    category: 'ai',
    icon: 'smile',
    inputFormats: ['.txt', '.md', '.html', '.json'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['ai', 'sentiment', 'emotion', 'nlp', 'analysis'],
    parameters: [],
  },
  {
    id: 'insert_pages',
    name: 'Insert PDF Pages',
    description: 'Insert pages from a source PDF into another target PDF at a specific page position',
    category: 'pdf',
    icon: 'plus-square',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 2,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'insert', 'pages', 'combine'],
    parameters: [],
  },
  {
    id: 'duplicate_pages',
    name: 'Duplicate PDF Pages',
    description: 'Duplicate specified pages in a PDF document',
    category: 'pdf',
    icon: 'copy',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'duplicate', 'pages', 'copy'],
    parameters: [],
  },
  {
    id: 'swap_pages',
    name: 'Swap PDF Pages',
    description: 'Swap the position of two pages in a PDF document',
    category: 'pdf',
    icon: 'repeat',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'swap', 'reorder', 'pages'],
    parameters: [
      { name: 'pageA', type: 'number', label: 'First Page #', description: 'Page number A', required: true, default: 1 },
      { name: 'pageB', type: 'number', label: 'Second Page #', description: 'Page number B', required: true, default: 2 },
    ],
  },
  {
    id: 'reverse_pages',
    name: 'Reverse PDF Page Order',
    description: 'Reverse the order of all pages in a PDF document',
    category: 'pdf',
    icon: 'rewind',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'reverse', 'order', 'pages'],
    parameters: [],
  },
  {
    id: 'edit_pdf_metadata',
    name: 'Edit PDF Metadata',
    description: 'Modify Title, Author, Subject, Creator, and Producer properties of a PDF',
    category: 'pdf',
    icon: 'edit-3',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'metadata', 'edit', 'properties'],
    parameters: [
      { name: 'title', type: 'string', label: 'Title', description: 'Document title', required: false },
      { name: 'author', type: 'string', label: 'Author', description: 'Author name', required: false },
    ],
  },
  {
    id: 'flatten_pdf_form',
    name: 'Flatten Interactive Form',
    description: 'Flatten interactive form fields into permanent page content',
    category: 'pdf',
    icon: 'layers',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'flatten', 'form', 'fields'],
    parameters: [],
  },
  {
    id: 'extract_form_fields',
    name: 'Extract Form Fields',
    description: 'Inspect and extract interactive form field names and types from PDF',
    category: 'pdf',
    icon: 'list',
    inputFormats: ['.pdf'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'fields', 'form', 'json', 'inspect'],
    parameters: [],
  },
  {
    id: 'pdf_to_txt',
    name: 'PDF to TXT',
    description: 'Extract raw text content from PDF into a clean plain text file',
    category: 'pdf',
    icon: 'file-text',
    inputFormats: ['.pdf'],
    outputFormats: ['.txt'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'txt', 'text', 'convert'],
    parameters: [],
  },
  {
    id: 'txt_to_pdf',
    name: 'TXT to PDF',
    description: 'Convert plain text (.txt) file into a formatted PDF document',
    category: 'pdf',
    icon: 'file',
    inputFormats: ['.txt'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 100 * MB,
    tags: ['txt', 'pdf', 'convert', 'document'],
    parameters: [],
  },
  {
    id: 'crop_pdf',
    name: 'Crop PDF Margins',
    description: 'Crop PDF page boundaries and outer whitespace margins',
    category: 'pdf',
    icon: 'crop',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'crop', 'margins', 'page'],
    parameters: [],
  },
  {
    id: 'resize_pdf_pages',
    name: 'Resize PDF Page Size',
    description: 'Resize or scale PDF pages to standard paper sizes (A4, Letter, A3)',
    category: 'pdf',
    icon: 'maximize-2',
    inputFormats: ['.pdf'],
    outputFormats: ['.pdf'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'resize', 'scale', 'a4', 'letter'],
    parameters: [],
  },
  {
    id: 'validate_pdf',
    name: 'Validate PDF File',
    description: 'Verify structural validity, integrity, and inspect properties of a PDF document',
    category: 'pdf',
    icon: 'check-circle',
    inputFormats: ['.pdf'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 500 * MB,
    tags: ['pdf', 'validate', 'verify', 'integrity', 'inspect'],
    parameters: [],
  },
  {
    id: 'invert_image',
    name: 'Invert Image Colors',
    description: 'Invert colors of an image to create a negative photo effect',
    category: 'image',
    icon: 'sliders',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff', '.bmp'],
    outputFormats: ['.png', '.jpg', '.webp'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['image', 'invert', 'colors', 'negative'],
    parameters: [],
  },
  {
    id: 'gamma_image',
    name: 'Gamma Correction',
    description: 'Apply gamma correction to adjust image luminance',
    category: 'image',
    icon: 'sun',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff', '.bmp'],
    outputFormats: ['.png', '.jpg', '.webp'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['image', 'gamma', 'brightness', 'luminance'],
    parameters: [
      { name: 'gamma', type: 'number', label: 'Gamma Level', description: 'Gamma value (e.g. 2.2)', required: false, default: 2.2 },
    ],
  },
  {
    id: 'threshold_image',
    name: 'Image Thresholding',
    description: 'Apply binary black & white threshold to image',
    category: 'image',
    icon: 'contrast',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff', '.bmp'],
    outputFormats: ['.png', '.jpg', '.webp'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['image', 'threshold', 'black white', 'binary'],
    parameters: [],
  },
  {
    id: 'dominant_colors',
    name: 'Dominant Color Palette',
    description: 'Extract dominant color palette and channel statistics from image',
    category: 'image',
    icon: 'pie-chart',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.tiff', '.bmp'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['image', 'colors', 'palette', 'dominant', 'stats'],
    parameters: [],
  },
  {
    id: 'trim_transparent_edges',
    name: 'Trim Transparent Edges',
    description: 'Crop and trim transparent or solid color outer borders from image',
    category: 'image',
    icon: 'crop',
    inputFormats: ['.png', '.webp', '.avif', '.tiff'],
    outputFormats: ['.png', '.webp'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['image', 'trim', 'crop', 'transparent', 'borders'],
    parameters: [],
  },
  {
    id: 'merge_docx',
    name: 'Merge Word Documents',
    description: 'Merge multiple Word (.docx) files into a single unified document',
    category: 'document',
    icon: 'file-text',
    inputFormats: ['.docx'],
    outputFormats: ['.docx'],
    maxFiles: 10,
    maxFileSize: 200 * MB,
    tags: ['docx', 'word', 'merge', 'combine'],
    parameters: [],
  },
  {
    id: 'replace_text_docx',
    name: 'Find & Replace Word Text',
    description: 'Find and replace target text occurrences inside a Word document',
    category: 'document',
    icon: 'search',
    inputFormats: ['.docx'],
    outputFormats: ['.docx'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['docx', 'word', 'replace', 'find', 'search'],
    parameters: [
      { name: 'targetText', type: 'string', label: 'Target Text', description: 'Text to search for', required: true },
      { name: 'replacementText', type: 'string', label: 'Replacement Text', description: 'Replacement text', required: true },
    ],
  },
  {
    id: 'extract_docx_comments',
    name: 'Extract Word Comments',
    description: 'Extract reviewer comments and notes from a Word document',
    category: 'document',
    icon: 'message-square',
    inputFormats: ['.docx'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['docx', 'word', 'comments', 'notes', 'review'],
    parameters: [],
  },
  {
    id: 'word_count_docx',
    name: 'Word Count & Statistics',
    description: 'Calculate word count, character count, sentence count, and reading time in Word documents',
    category: 'document',
    icon: 'bar-chart-2',
    inputFormats: ['.docx'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['docx', 'word', 'count', 'stats', 'readability'],
    parameters: [],
  },
  {
    id: 'protect_workbook',
    name: 'Protect Excel Workbook',
    description: 'Add password protection and lock worksheet editing in Excel workbooks',
    category: 'spreadsheet',
    icon: 'lock',
    inputFormats: ['.xlsx', '.xls'],
    outputFormats: ['.xlsx'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['excel', 'spreadsheet', 'protect', 'lock', 'password'],
    parameters: [
      { name: 'password', type: 'string', label: 'Protection Password', description: 'Password for sheet protection', required: false, default: 'protected' },
    ],
  },
  {
    id: 'split_workbook',
    name: 'Split Excel Workbook',
    description: 'Split a multi-sheet Excel workbook into separate individual sheet files',
    category: 'spreadsheet',
    icon: 'scissors',
    inputFormats: ['.xlsx', '.xls'],
    outputFormats: ['.xlsx'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['excel', 'spreadsheet', 'split', 'sheets'],
    parameters: [],
  },
  {
    id: 'find_replace_excel',
    name: 'Find & Replace Excel Cells',
    description: 'Find and replace target cell values across all Excel worksheets',
    category: 'spreadsheet',
    icon: 'search',
    inputFormats: ['.xlsx', '.xls'],
    outputFormats: ['.xlsx'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['excel', 'spreadsheet', 'replace', 'find', 'search'],
    parameters: [
      { name: 'targetValue', type: 'string', label: 'Target Value', description: 'Text or number to search for', required: true },
      { name: 'replacementValue', type: 'string', label: 'Replacement Value', description: 'Replacement cell value', required: true },
    ],
  },
  {
    id: 'workbook_statistics',
    name: 'Workbook Statistics',
    description: 'Analyze Excel workbook structure, sheet counts, row counts, and stats',
    category: 'spreadsheet',
    icon: 'bar-chart-2',
    inputFormats: ['.xlsx', '.xls', '.csv'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['excel', 'spreadsheet', 'stats', 'rows', 'sheets'],
    parameters: [],
  },
  {
    id: 'pptx_to_html',
    name: 'PowerPoint to HTML Deck',
    description: 'Convert PowerPoint (.pptx) presentation slides into a web HTML slide deck',
    category: 'presentation',
    icon: 'layers',
    inputFormats: ['.pptx'],
    outputFormats: ['.html'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['powerpoint', 'pptx', 'html', 'slides', 'deck'],
    parameters: [],
  },
  {
    id: 'read_pptx_metadata',
    name: 'PowerPoint Metadata & Stats',
    description: 'Extract presentation slide counts, speaker notes count, media count, and metadata',
    category: 'presentation',
    icon: 'info',
    inputFormats: ['.pptx'],
    outputFormats: ['.json'],
    maxFiles: 1,
    maxFileSize: 200 * MB,
    tags: ['powerpoint', 'pptx', 'metadata', 'slides', 'stats'],
    parameters: [],
  },
];

// ─── Categories ──────────────────────────────────────────────

export const categories: CategoryInfo[] = [
  { id: 'pdf', name: 'PDF Tools', description: 'Merge, split, compress, and manipulate PDF documents', icon: 'file-text', toolCount: 0 },
  { id: 'image', name: 'Image Tools', description: 'Resize, crop, convert, and enhance images', icon: 'image', toolCount: 0 },
  { id: 'data', name: 'Data Conversion', description: 'Convert between JSON, XML, YAML, CSV, and more', icon: 'database', toolCount: 0 },
  { id: 'document', name: 'Word Documents', description: 'Process Word DOCX files, text, images, and HTML', icon: 'file', toolCount: 0 },
  { id: 'spreadsheet', name: 'Spreadsheets', description: 'Excel XLSX/XLS workbooks, CSV, sheet merging, and deduplication', icon: 'table', toolCount: 0 },
  { id: 'presentation', name: 'PowerPoint', description: 'PowerPoint PPTX slides, text, speaker notes, and image extraction', icon: 'layers', toolCount: 0 },
  { id: 'text', name: 'Text & Readability', description: 'Word count, character analysis, readability metrics, and statistics', icon: 'info', toolCount: 0 },
  { id: 'audio', name: 'Audio', description: 'Convert, trim, merge, and process audio files', icon: 'music', toolCount: 0 },
  { id: 'video', name: 'Video', description: 'Convert, compress, trim, and edit video files', icon: 'video', toolCount: 0 },
  { id: 'archive', name: 'Archives', description: 'Compress and extract ZIP, RAR, 7Z, and more', icon: 'archive', toolCount: 0 },
  { id: 'ocr', name: 'OCR', description: 'Extract text from images and scanned documents', icon: 'scan', toolCount: 0 },
  { id: 'metadata', name: 'Metadata', description: 'Read, edit, and remove file metadata', icon: 'tag', toolCount: 0 },
  { id: 'ai', name: 'AI Tools', description: 'Summarize, translate, and analyze with AI', icon: 'brain', toolCount: 0 },
];

// Update tool counts
categories.forEach(cat => {
  cat.toolCount = tools.filter(t => t.category === cat.id).length;
});

// ─── Registry Functions ──────────────────────────────────────

export function getTools(): ToolDefinition[] {
  return tools;
}

export function getToolById(id: string): ToolDefinition | undefined {
  return tools.find(t => t.id === id);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return tools.filter(t => t.category === category);
}

export function searchTools(query: string): ToolDefinition[] {
  const q = query.toLowerCase();
  return tools.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.toLowerCase().includes(q)) ||
    t.id.toLowerCase().includes(q)
  );
}

export function getCategories(): CategoryInfo[] {
  return categories.filter(c => c.toolCount > 0);
}

export function getActiveCategories(): CategoryInfo[] {
  return categories.filter(c => c.toolCount > 0);
}
